name: Hardhat Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - release/**
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      
      - name: "Install the Node.Js dependencies"
        run: "npm install"
      - name: "Compile code"
      - run: "npm run compile"
