name: Hardhat Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

env:
  PRIVATE_KEY1: ${{ secrets.PRIVATE_KEY1 }}
  PRIVATE_KEY2: ${{ secrets.PRIVATE_KEY2 }}

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - release/**
jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY1: ${{ secrets.PRIVATE_KEY1 }}
      PRIVATE_KEY2: ${{ secrets.PRIVATE_KEY2 }}

    steps:
      - uses: actions/checkout@v3

      - name: Install / packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: npm install

      - name: Compile code
      - run: npm run compile
