name: Hardhat Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - release/**
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      - name: Hardhat Solidity
        uses: amine7777/hardhat-action@v1
  
