name: Hardhat Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - release/**
jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set ENVs
        env:
          PRIVATE_KEY1: ${{ secrets.PRIVATE_KEY_1 }}
          PRIVATE_KEY2: ${{ secrets.PRIVATE_KEY_2 }}
      - name: Install / packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: npm install
      - name: Compile code
      - run: npm run compile
