name: Hardhat Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compiling the Whole Solidity code
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run compile
