name: Hardhat Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - release/**
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: npm install
      - run: npm run compile
