name: Hardhat CI
run-name: ${{ github.actor }} is pushing new version on GitHub Actions 🚀
env: 
  PRIVATE_KEY_1: ${{ secrets.PRIVATE_KEY_1 }}
  PRIVATE_KEY_2: ${{ secrets.PRIVATE_KEY_2 }}
on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - release/**
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: npm install
      - run: npm run compile
